config/routes.rb
Katalog::Application.routes.draw do

  root :to => 'application#root'

  resources :projects, :only => [:create, :show, :index, :edit, :update, :destroy] do
    root to: 'projects#index'

    collection do
      get :mine
      get :ideas
      get :lifted
      get :sync
      get :random
      get '/user/:username', to: :user, as: :user
    end

    member do
      post :lift
      post :contribute
    end

    resources :posts, :only => [:create, :destroy]
    resources :users, :only => [:create, :destroy]
  end

  resource :autocomplete, :controller => 'autocomplete', :only => [] do
    get :users
    get :projects
  end

  post '/postmark', to: 'postmark#update'
  get '/slack', to: 'slack#show'
  post '/slack', to: 'slack#create'

  # authentication
  match '/auth/:provider/callback', :to => 'session#create', :via => [:get, :post]
  get '/auth/destroy', :to => 'session#destroy', :as => 'sign_out'
  get '/auth/failure', :to => 'session#failure'
  get '/auth/github', :to => 'session#nothing', :as => 'sign_in'
  post '/auth/organization', :to => 'session#organization', :as => 'organization'
  get '/auth/organization/change', :to => 'session#change_organization', :as => 'change_organization'

  get '404', :to => 'static#not_found'
  get '401', :to => 'static#not_found'
  get '403', :to => 'static#forbidden'
  get '500', :to => 'static#internal_error'
  get '422', :to => 'static#internal_error'

end

app/views/projects/show/project_sidebar/_collaborators.html.haml
%hr
  - unless collaborator?
    = link_to project_users_path(current_project), method: :post, class: 'btn btn-xs btn-default pull-right' do
      %i.fa.fa-user
      = t('.im_collaborator')
  %h4= t('.collaborators')
  .collaborators
    - current_project.users.each do |user|
      .user.media
        .avatar-contrainer.pull-left
          = render 'users/avatar', user: user
        .media-body
          = link_to project_user_path(current_project, user), method: :delete, class: 'btn-remove btn btn-xs btn-danger pull-right', data: {confirm: t('.are_you_sure_collaborators')} do
            %i.fa.fa-times-circle
            = t('.remove')
          %strong.lead= user.name
          - if current_project.ideator == user
            .text-muted= t('.ideator')

app/views/projects/show/project_sidebar/_details.html.haml
%hr
.project-details
  %dl.dl-horizontal
    %dt= t('.added_on')
    %dd= current_project.created_at.strftime('%d/%m/%Y')
    - if current_project.lifted_at.present?
      %dt= t('.lifted_on')
      %dd= current_project.lifted_at.strftime('%d/%m/%Y')
    %dt Last updated on
    %dd= current_project.updated_at.strftime('%d/%m/%Y')
    %dd
    - if current_project.repo_url.present?
      %dt
        %i.fa.fa-github-square
        =t('.repo_label')
      %dd
        = link_to current_project.repo_url, :class => 'a-link' do
          %span= t('.repo_url')
    - if current_project.demo_url.present?
      %dt
        %i.fa.fa-globe
        =t('.demo_label')
      %dd
        = link_to current_project.demo_url, :class => 'a-link' do
          %span= t('.demo_url')

app/views/projects/show/project_sidebar/_image.html.haml
.project-image
  = form_for current_project, html: {class: 'hidden' } do |f|
    = f.text_field :image_url
  = file_field :project, :image_url, accept: 'image/*', class: 'hidden file-field'
  %btn.btn.btn-default.btn-sm.upload-image
    %i.fa.fa-image
    = t('.upload_image')
  = image_tag project_image(current_project)