config/routes.rb
Katalog::Application.routes.draw do

  root :to => 'application#root'

  resources :projects, :only => [:create, :show, :index, :edit, :update, :destroy] do
    root to: 'projects#index'

    collection do
      get :mine
      get :ideas
      get :lifted
      get :sync
      get :random
      get '/user/:username', to: :user, as: :user
    end

    member do
      post :lift
      post :contribute
    end

    resources :posts, :only => [:create, :destroy]
    resources :users, :only => [:create, :destroy]
  end

  resource :autocomplete, :controller => 'autocomplete', :only => [] do
    get :users
    get :projects
  end

  post '/postmark', to: 'postmark#update'
  get '/slack', to: 'slack#show'
  post '/slack', to: 'slack#create'

  # authentication
  match '/auth/:provider/callback', :to => 'session#create', :via => [:get, :post]
  get '/auth/destroy', :to => 'session#destroy', :as => 'sign_out'
  get '/auth/failure', :to => 'session#failure'
  get '/auth/github', :to => 'session#nothing', :as => 'sign_in'
  post '/auth/organization', :to => 'session#organization', :as => 'organization'
  get '/auth/organization/change', :to => 'session#change_organization', :as => 'change_organization'

  get '404', :to => 'static#not_found'
  get '401', :to => 'static#not_found'
  get '403', :to => 'static#forbidden'
  get '500', :to => 'static#internal_error'
  get '422', :to => 'static#internal_error'

end

app/views/layouts/components/_background.html.haml
.background.blur
.background.overlay

app/views/layouts/components/_clouds.html.haml
.cloud{:style => 'top: -2%; left:-2%'}
.cloud.flipped{:style => 'top: 83%; left: -12%'}
.cloud.small.flipped{:style => 'top: 46%; left: -5%'}
.cloud.flipped.hidden-xs{:style => 'top: 15%; left: 60%'}
.cloud{:style => 'top: 60%; left: 76%'}
.cloud.flipped.small{:style => 'top: 35%; left: 87%'}
.cloud.small.flipped.hidden-xs{:style => 'top: 83%; left: 59%'}
.cloud.small{:style => 'top: 30%; left: 17%'}
.cloud.small.hidden-xs{:style => 'top: 57%; left: 25%'}
.cloud.small.flipped.hidden-xs{:style => 'top: 12%; left: 28%'}

app/views/layouts/components/_footer.html.haml
%footer{ class_if('headless', headless_page?) }
  %p
    %strong Katalog
    was created by the
    = link_to 'Not Ninjas', 'http://notninjas.com', target: '_blank'
    at the eBay Israel Innovation Center.
    %br
    Feel free to go over the code, suggest new features and fix bugs over on
    = link_to 'https://github.com/TheGiftsProject/katalog', target: '_blank' do
      %i.fa.fa-github
      GitHub

app/views/layouts/components/_header.html.haml
%nav.navbar.navbar-default{:role => 'navigation'}
  .container
    .navbar-header
      %button.navbar-toggle{type: :button, data: {toggle: :collapse, target: "#navbar-collapse"}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to projects_path, class: 'navbar-brand uppercase' do
        = image_tag('logo-small.png', :class => 'logo')
        %span.brand-title= t('site.title')

    .navbar-collapse.collapse#navbar-collapse
      %ul.nav.navbar-nav.navbar-left
        = render 'layouts/components/header_pill', path: projects_path, icon: 'fa-list', text: :all
        = render 'layouts/components/header_pill', path: mine_projects_path, icon: 'fa-child', text: :mine
        = render 'layouts/components/header_pill', path: ideas_projects_path, icon: 'fa-lightbulb-o', text: :ideas
        = render 'layouts/components/header_pill', path: lifted_projects_path, icon: 'fa-paper-plane', text: :lifted
        = render 'layouts/components/header_pill', path: sync_projects_path, icon: 'fa-refresh', text: :sync

      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{:href => '#', :data => {:toggle => 'dropdown'}}
            = render 'users/avatar_img', :user => current_user, :type => 'tiny'
            = current_user.name
            %span.caret
            %ul.dropdown-menu{:style => 'min-width: 100%;'}
              %li
                %a{:href => change_organization_path}
                  %i.fa.fa-github
                  %span= t('.change_organization', :name => current_user.default_organization.name)
              %li
                %a{:href => sign_out_path}
                  %i.fa.fa-sign-out
                  %span= t('.sign_out')

      %form.navbar-form.navbar-right.hidden-sm{:role => 'search'}
        .form-group
        = text_field_tag :query, nil, :placeholder => t('.search_placeholder'), :class => 'form-control search-query', :autocomplete => :off

app/views/layouts/components/_header_pill.html.haml
%li.nav-pill{ active_class_if_page(path) }
  = link_to path do
    %i.fa.fa-fw{class: icon}
    %span.uppercase= t(text, :scope => 'layouts.header.pills')

app/views/layouts/components/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? "success" : "danger"}"}
      %a.close{'data-dismiss' => 'alert'} ×
      = content_tag :div, msg, :id => "flash_#{name}"

- unless headless_page?
  :coffee
    setTimeout ->
      $(".alert").fadeTo(250, 0).slideUp(500, -> $(this.remove()))
    , 3000