config/routes.rb
Katalog::Application.routes.draw do

  root :to => 'application#root'

  resources :projects, :only => [:create, :show, :index, :edit, :update, :destroy] do
    root to: 'projects#index'

    collection do
      get :mine
      get :ideas
      get :lifted
      get :sync
      get :random
      get '/user/:username', to: :user, as: :user
    end

    member do
      post :lift
      post :contribute
    end

    resources :posts, :only => [:create, :destroy]
    resources :users, :only => [:create, :destroy]
  end

  resource :autocomplete, :controller => 'autocomplete', :only => [] do
    get :users
    get :projects
  end

  post '/postmark', to: 'postmark#update'
  get '/slack', to: 'slack#show'
  post '/slack', to: 'slack#create'

  # authentication
  match '/auth/:provider/callback', :to => 'session#create', :via => [:get, :post]
  get '/auth/destroy', :to => 'session#destroy', :as => 'sign_out'
  get '/auth/failure', :to => 'session#failure'
  get '/auth/github', :to => 'session#nothing', :as => 'sign_in'
  post '/auth/organization', :to => 'session#organization', :as => 'organization'
  get '/auth/organization/change', :to => 'session#change_organization', :as => 'change_organization'

  get '404', :to => 'static#not_found'
  get '401', :to => 'static#not_found'
  get '403', :to => 'static#forbidden'
  get '500', :to => 'static#internal_error'
  get '422', :to => 'static#internal_error'

end

app/models/concerns/project/github_concern.rb
module Project::GithubConcern
  extend ActiveSupport::Concern

  # Goes into Project

  # Example: current_project.github_readme, etc...
  delegate :readme,
           :todo,
           :changelog,
           :to => :github_grabber, :prefix => :github

  def includes_contributors?(contributors_emails)
    current_contributors_emails = Set.new(self.users.map(&:email))
    new_contributors_emails = Set.new(contributors_emails)
    new_contributors_emails.subset?(current_contributors_emails)
  end

  # Compares the current Project's repo to a given repo url or Project's repo url
  #
  # @param repo [String, Project] Either a A GitHub repository url or a Project model
  def same_repo?(repo)
    repo = repo.repo_url if repo.is_a? Project
    current_repo = Octokit::Repository.from_url(self.repo_url)
    other_repo = Octokit::Repository.from_url(repo)
    current_repo.slug == other_repo.slug
  end

  def has_a_repo?
    self.repo_url.present?
  end

  private

  def github_grabber
    @github_grabber ||= Github::Grabber.new(self) if has_a_repo?
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :ideator, :class_name => 'User'
  belongs_to :organization
  has_and_belongs_to_many :users
  has_many :posts, :dependent => :destroy
  has_many :project_updates, :dependent => :destroy

  self.per_page = 8

  enum :status, [:idea, :lifted]

  GITHUB_REPO_HOST = 'https://github.com/'

  scope :have_github_repo, -> { where("repo_url LIKE '#{GITHUB_REPO_HOST}%'") }
  scope :latest_first, -> { order('projects.updated_at DESC') }
  scope :search, -> (query) { query.blank? ? none : where('lower(title) like ? or lower(title) like ?',
                                                              "#{query.downcase}%", "% #{query.downcase}%")}
  scope :of_user, -> (user) { includes(:users).where(:users => {:id => user.id}) }
  scope :order_by_user_update, -> (user, time) { includes(:project_updates).
                                                 where('project_updates.user_id = ?', user.id).
                                                 order("CASE WHEN (project_updates.updated_at >= '#{time.ago}') THEN (projects.updated_at) ELSE (project_updates.updated_at) END DESC")
                                               }

  validates_presence_of :title

  def to_param
    slug
  end

  def less_than_week_old?
    self.created_at > 1.week.ago
  end

  def ideator
    self[:ideator].presence || users.first
  end

  def lift!
    update(
      lifted_at: DateTime.now,
      status: :lifted
    )
  end

  def github_repo_name
    return nil if repo_url.blank?
    repo_url.sub(GITHUB_REPO_HOST, '')
  end

  private

  def slug
    "#{id}-#{title.parameterize}"
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  DEFAULT_FILTER = :all
  SYNC_PROJECT_LIMIT = 3
  SYNC_UPDATE_TIME_THRESHOLD = 1.months

  include ProjectSupport

  before_filter :sign_in_required
  before_filter :project_required, :only => [:show, :edit, :update, :destroy]
  before_filter :save_referer, :only => [:show]
  before_filter :reset_referer, :only => [:index]
  before_filter :random_idea, only: [:index, :mine, :sync, :ideas, :lifted, :user]
  after_filter :set_viewed_cookie, :only => [:create, :show]
  after_filter :set_project_update_for_current_user, :only => [:create, :lift, :update, :contribute]

  def index
    set_projects_for_scope(scoped_projects)
  end

  def mine
    set_projects_for_scope(scoped_projects.of_user(current_user))
    render action: :index
  end

  def lifted
    set_projects_for_scope(scoped_projects.lifted)
    render action: :index
  end

  def ideas
    set_projects_for_scope(scoped_projects.idea)
    render action: :index
  end

  def user
    @user = current_organization.users.find_by(nickname: params[:username])
    redirect_to root_path and return unless @user.present?
    set_projects_for_scope(scoped_projects.of_user(@user))
    render action: :index
  end

  def sync
    seed = Time.now.beginning_of_week.to_i
    rand = Random.new(seed)
    users = current_organization.users.no_hidden.order(:id).to_a.shuffle(:random => rand)
    @user_projects = users_projects(users)
  end

  def random
    random_idea
    render partial: 'projects/index/random_idea', layout: false
  end

  #########

  def show
    @post = current_project.posts.build
  end

  def create
    @project = build_project
    if @project.save
      set_current_project(@project)
      redirect_to :back, notice: t('notices.created')
    else
      flash[:error] = @project.errors.full_messages.join(', ')
      redirect_to :back
    end
  end

  def edit
  end

  def lift
    current_project.lift!
    redirect_to current_project, notice: t('notices.lifted')
  end

  def update
    if current_project.update(project_params)
      current_project.lift! if current_project.repo_url.present? && current_project.idea?
      redirect_to current_project, notice: t('notices.updated')
    else
      render action: 'edit'
    end
  end

  def destroy
    current_project.destroy
    redirect_to projects_path, notice: t('notices.destroyed')
  end

  def contribute
    add_user_to_project
    redirect_to current_project, notice: t('notices.contribute')
  end

  private

  def add_user_to_project
    current_project.users << current_user unless current_project.users.include? current_user
  end

  def project_params
    params.require(:project).permit([:title, :subtitle, :demo_url, :repo_url, :image_url])
  end

  def build_project
    project = current_user.projects.build(project_params)
    project.users = [current_user]
    project.ideator_id = current_user.id
    project.organization_id = current_user.default_organization_id
    project
  end

  def set_projects_for_scope(scope)
    @projects = scope.latest_first.paginate(:page => params[:page])
  end

  def random_idea
    @random_project = scoped_projects.idea.to_a.sample
  end

  def users_projects(users)
    users_projects = users.map { |user| {:user => user, :projects => sync_projects(user) } }
    users_projects.delete_if { |user_projects| user_projects[:projects].blank? }
  end

  def sync_projects(user)
    scoped_projects.
    of_user(user).
    limit(SYNC_PROJECT_LIMIT).
    order_by_user_update(user, SYNC_UPDATE_TIME_THRESHOLD)
  end

end

app/helpers/project_helper.rb
module ProjectHelper

  def class_for_quick_idea
    hide_quick_idea? ? 'hidden-xs' : ''
  end

  def hide_quick_idea?
    !(current_page? projects_path)
  end

  def new_for_current_user?(project)
    project.less_than_week_old? and not viewed_by_current_user?(project)
  end

  def viewed_by_current_user?(project)
    viewed_hash = cookies[:viewed]
    return false unless viewed_hash
    JSON.parse(viewed_hash)[project.id.to_s]
  end

  def back_to_index_url
    session[:referer] || projects_path
  end

  def collaborator?
    current_project.users.include? current_user
  end

  def project_image(project)
    project.image_url || image_path('no-image.png')
  end

  def last_updated_time(project, user = nil)
    if user.nil?
      project.updated_at
    else
      my_project_update = user.project_updates.find_by(:project_id => project.id)
      if my_project_update.updated_at < ProjectsController::SYNC_UPDATE_TIME_THRESHOLD.ago
        my_project_update.updated_at
      else
        sync_project_update = project.project_updates.updated_in(ProjectsController::SYNC_UPDATE_TIME_THRESHOLD).latest_first.first
        sync_project_update.updated_at
      end
    end
  end

end

app/views/projects/show/_add_post.html.haml
= form_for [project, post], :html => {:class => 'form-horizontal'} do |f|
  .form-group
    .post.col-sm-12
      .tabbable
        %ul.nav.nav-pills
          %li.active
            %a{:href => '#text', :data => {:toggle => 'tab'}}= t('.tabs.text')
          %li
            %a{:href => '#preview', :data => {:toggle => 'tab'}}= t('.tabs.preview')
        .tab-content
          #text.tab-pane.active
            = f.text_area :text, :rows => 3, :placeholder => t('.placeholder'), :class => 'markdown-text'
          #preview.tab-pane
            .markdown-preview
      - unless project.new_record?
        .status-fields
          = f.submit :class => 'btn btn-primary pull-right'

app/views/projects/show/_comment.html.haml
.comment.media
  %strong.lead
    = render 'users/avatar_img', :user => post.user, type: :tiny
    = post.user.name
  .when.pull-right
    %span.text-muted= t('.time_ago', :time_ago => time_ago_in_words(post.created_at))
    - if current_user == post.user
      .actions
        %span.text-muted= '|'
        = link_to [current_project, post], :method => :delete do
          %i.fa.fa-times{:title => t('.delete_post')}

  .body
    ~ markdown.render(post.text).html_safe
  %hr

app/views/projects/show/_comments.html.haml
.comments
  %h2= t('.title')
  .well.well-sm
    - if current_project.posts.count==0
      .lead.text-center.well-lg#be-the-first
        %i.fa.fa-list
        = t('.be_the_first')
    - current_project.posts.each do |post|
      - if post.persisted?
        = render 'projects/show/comment', :post => post
    = render 'projects/show/add_post', :project => current_project, :post => @post

app/views/projects/show/_info_box.html.haml
.info-box.pull-right
  = image_tag 'http://lorempixel.com/200/150/business/'
  = link_to 'Repo URL', current_project.repo_url
  = link_to 'Demo URL', current_project.demo_url

app/views/projects/show/_project_sidebar.html.haml
- if has_saved_referer? and current_page? project_path
  = link_to back_to_index_url, {:class => 'hidden-sm hidden-xs'} do
    %h4
      %i.fa.fa-long-arrow-left
      %span= t('.back')

= render :partial => 'projects/show/project_sidebar/image'
%h1.break-word= current_project.title
%p.lead.break-word= current_project.subtitle
= render :partial => 'projects/show/project_sidebar/details'
= render :partial => 'projects/show/project_sidebar/collaborators'

app/views/projects/show/_toolbar.html.haml
.project-toolbar
  - unless current_project.lifted?
    &nbsp;
    = link_to lift_project_path, method: :post, class: 'btn btn-primary' do
      %i.fa.fa-paper-plane
      %span= t('.lift')
  &nbsp;
  = link_to edit_project_path(current_project), class: 'btn btn-default' do
    %i.fa.fa-edit
    = t('.edit')