config/routes.rb
Katalog::Application.routes.draw do

  root :to => 'application#root'

  resources :projects, :only => [:create, :show, :index, :edit, :update, :destroy] do
    root to: 'projects#index'

    collection do
      get :mine
      get :ideas
      get :lifted
      get :sync
      get :random
      get '/user/:username', to: :user, as: :user
    end

    member do
      post :lift
      post :contribute
    end

    resources :posts, :only => [:create, :destroy]
    resources :users, :only => [:create, :destroy]
  end

  resource :autocomplete, :controller => 'autocomplete', :only => [] do
    get :users
    get :projects
  end

  post '/postmark', to: 'postmark#update'
  get '/slack', to: 'slack#show'
  post '/slack', to: 'slack#create'

  # authentication
  match '/auth/:provider/callback', :to => 'session#create', :via => [:get, :post]
  get '/auth/destroy', :to => 'session#destroy', :as => 'sign_out'
  get '/auth/failure', :to => 'session#failure'
  get '/auth/github', :to => 'session#nothing', :as => 'sign_in'
  post '/auth/organization', :to => 'session#organization', :as => 'organization'
  get '/auth/organization/change', :to => 'session#change_organization', :as => 'change_organization'

  get '404', :to => 'static#not_found'
  get '401', :to => 'static#not_found'
  get '403', :to => 'static#forbidden'
  get '500', :to => 'static#internal_error'
  get '422', :to => 'static#internal_error'

end

app/views/layouts/_background.html.haml
.background-wrapper{:class => if blank_page? then 'blank' end}
  .select-stopper
  = image_tag("/backgrounds/#{background}.jpg", :class => 'background-image')

app/views/layouts/_header.html.haml
%header.navbar
  .navbar-inner
    = link_to projects_path do
      = image_tag('logo/logo-small.png', :class => 'logo')
      .brand= t('site.title')
    %form.navbar-search
      = text_field_tag :query, nil, :placeholder => t('layout.header.search_placeholder'), :class => 'input-long search-query', :autocomplete => :off
    %ul.user-dashboard.nav.pull-right
      - if user_signed_in?
        %li.dropdown
          %a.dropdown-toggle{:href => '#', :data => {:toggle => 'dropdown'}}
            - if current_user.image.present?
              = render 'users/avatar_img', :user => current_user
            %strong= current_user.nickname
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to t('layout.header.links.projects'), projects_path
            %li
              = link_to t('layout.header.links.zen'), zen_path
            %li
              = link_to t('layout.header.links.sign_out'), sign_out_path
      - else
        %li
          = link_to t('layout.header.links.sign_in'), sign_in_path

app/views/layouts/application.html.haml
!!! 5
%html.no-js{:lang => 'en'}
  %head
    %meta{:charset => 'utf-8'}
    %title= t('site.title')
    %meta{:name => 'description', :content => t('site.description')}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1, user-scalable=no'}

    %link{:href => '/favicon.png', :rel => 'shortcut icon'}

    %link{:href => '/apple-icon-60x60.png', :rel => 'apple-touch-icon'}
    %link{:href => '/apple-icon-76x76.png', :rel => 'apple-touch-icon', :sizes => '76x76'}
    %link{:href => '/apple-icon-120x120.png', :rel => 'apple-touch-icon', :sizes => '120x120'}
    %link{:href => '/apple-icon-152x152.png', :rel => 'apple-touch-icon', :sizes => '152x152'}

    = csrf_meta_tags
    = stylesheet_link_tag 'application', 'data-turbolinks-track' => true, :media => 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body
    - unless headless_page?
      = render 'layouts/components/header'
    .container
      = render 'layouts/components/messages'
      = yield
    = render 'layouts/components/footer'
    - if headless_page?
      = render 'layouts/components/clouds'
    - yield :bottom_javascripts
    = configure_s3_storage